workflows:
  ios-build:
    name: iOS Build
    instance_type: mac_mini_m2
    scripts:
      - name: Build Flutter iOS
        script: |
          flutter pub get
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app